# Generated by Django 3.0.6 on 2020-05-28 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='level_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='level_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='level_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='level_4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='plate_text_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='plate_text_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='plate_text_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='plate_text_4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill_4',
        ),
    ]
